# Generated by Django 5.0.4 on 2024-05-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colorphoto',
            field=models.ManyToManyField(blank=True, related_name='product_colorphoto', to='store.colorphoto'),
        ),
    ]
