# Generated by Django 5.0.4 on 2024-05-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_colorphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorphoto',
            name='photos',
            field=models.ManyToManyField(related_name='photos', to='store.photo'),
        ),
    ]
