# Generated by Django 5.0.4 on 2024-05-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_colorphoto_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stars',
        ),
    ]
