# Generated by Django 5.0.4 on 2024-05-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='reviews',
        ),
        migrations.AddField(
            model_name='reviews',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
