# Generated by Django 5.0.4 on 2024-05-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_reviews_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='data',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
