# Generated by Django 5.0.4 on 2024-05-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_reviews_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='text',
            field=models.TextField(null=True, verbose_name='Reviews'),
        ),
    ]
